version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: socialDev
    restart: always
    tty: true
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - dockernet
    ports:
      - 3399:3306

networks:
  dockernet:
    driver: bridge